# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "ayden" ]
  pull_request:
    branches: [ "ayden" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        wget https://github.com/HeaTTheatR/KivyMD-data/raw/master/install-kivy-buildozer-dependencies.sh
        chmod +x install-kivy-buildozer-dependencies.sh
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install libc6:i386 libncurses5:i386 libstdc++6:i386 lib32z1 libbz2-1.0:i386
        ./install-kivy-buildozer-dependencies.sh
        pip install kivymd
        sudo pip install Cython==0.17.1
        sudo apt install default-jre
    - name: Build APK
      run: |
        buildozer android debug
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
    # Artifact name
        name: # optional, default is artifact
    # A file, directory or wildcard pattern that describes what to upload
        path: ./bin
